import type { RouteRecordRaw } from "vue-router";

export const inventoryRoutes: RouteRecordRaw[] = [
  {
    path: "branches",
    name: "branches.index",
    component: () => import("./pages/BranchesIndexPage.vue"),
    meta: { permission: "read-branch" },
  },
  {
    path: "branches/create",
    name: "branches.create",
    component: () => import("./pages/BranchFormPage.vue"),
    meta: { permission: "create-branch" },
  },
  {
    path: "branches/:id/edit",
    name: "branches.edit",
    component: () => import("./pages/BranchFormPage.vue"),
    props: true,
    meta: { permission: "update-branch" },
  },
  {
    path: "products",
    name: "products.index",
    component: () => import("./pages/ProductsIndexPage.vue"),
    meta: {
      permission: [
        "view-all-product",
        "view-own-product",
        "read-product",
        "create-product",
        "update-product",
        "delete-product",
      ],
    },
  },
  {
    path: "products/create",
    name: "products.create",
    component: () => import("./pages/ProductFormPage.vue"),
    meta: { permission: "create-product" },
  },
  {
    path: "products/create-with-items",
    name: "products.create-with-items",
    component: () => import("./pages/ProductWithItemsFormPage.vue"),
    meta: { permission: "create-product" },
  },
  {
    path: "products/:id/edit",
    name: "products.edit",
    component: () => import("./pages/ProductFormPage.vue"),
    props: true,
    meta: { permission: "update-product" },
  },
  {
    path: "product-items",
    name: "product-items.index",
    component: () => import("./pages/ProductItemsIndexPage.vue"),
    meta: {
      permission: [
        "view-all-product-item",
        "view-own-product-item",
        "read-product-item",
        "create-product-item",
        "update-product-item",
        "delete-product-item",
      ],
    },
  },
  {
    path: "product-items/create",
    name: "product-items.create",
    component: () => import("./pages/ProductItemFormPage.vue"),
    meta: { permission: "create-product-item" },
  },
  {
    path: "product-items/:id/edit",
    name: "product-items.edit",
    component: () => import("./pages/ProductItemFormPage.vue"),
    props: true,
    meta: { permission: "update-product-item" },
  },
  {
    path: "product-options",
    name: "product-options.index",
    component: () => import("./pages/ProductOptionsIndexPage.vue"),
    meta: {
      permission: [
        "read-product-option",
        "view-all-product-option",
        "view-own-product-option",
        "create-product-option",
        "update-product-option",
        "delete-product-option",
      ],
    },
  },
  {
    path: "product-options/create",
    name: "product-options.create",
    component: () => import("./pages/ProductOptionFormPage.vue"),
    meta: { permission: "create-product-option" },
  },
  {
    path: "product-options/:id/edit",
    name: "product-options.edit",
    component: () => import("./pages/ProductOptionFormPage.vue"),
    props: true,
    meta: { permission: "update-product-option" },
  },
  {
    path: "customers",
    name: "customers.index",
    component: () => import("./pages/CustomersIndexPage.vue"),
    meta: {
      permission: [
        "view-all-customer",
        "view-own-customer",
        "view-customer",
        "read-customer",
        "create-customer",
        "update-customer",
        "delete-customer",
      ],
    },
  },
  {
    path: "customers/create",
    name: "customers.create",
    component: () => import("./pages/CustomerFormPage.vue"),
    meta: { permission: "create-customer" },
  },
  {
    path: "customers/:id/edit",
    name: "customers.edit",
    component: () => import("./pages/CustomerFormPage.vue"),
    props: true,
    meta: { permission: "update-customer" },
  },
  {
    path: "merchants",
    name: "merchants.index",
    component: () => import("./pages/MerchantsIndexPage.vue"),
    meta: {
      permission: ["view-all-merchant", "view-own-merchant"],
      permissionAll: ["read-merchant"],
    },
  },
  {
    path: "merchants/create",
    name: "merchants.create",
    component: () => import("./pages/MerchantFormPage.vue"),
    meta: { permission: "create-merchant" },
  },
  {
    path: "merchants/:id/edit",
    name: "merchants.edit",
    component: () => import("./pages/MerchantFormPage.vue"),
    props: true,
    meta: {
      permission: ["view-all-merchant", "view-own-merchant"],
      permissionAll: ["read-merchant", "update-merchant"],
    },
  },
  {
    path: "warehouses",
    name: "warehouses.index",
    component: () => import("./pages/WarehousesIndexPage.vue"),
    meta: {
      permission: [
        "view-all-warehouse",
        "view-own-warehouse",
        "view-warehouse",
        "read-warehouse",
        "create-warehouse",
        "update-warehouse",
        "delete-warehouse",
      ],
    },
  },
  {
    path: "warehouses/create",
    name: "warehouses.create",
    component: () => import("./pages/WarehouseFormPage.vue"),
    meta: {
      permission: "create-warehouse",
      permissionAll: ["read-branch"],
    },
  },
  {
    path: "warehouses/:id/edit",
    name: "warehouses.edit",
    component: () => import("./pages/WarehouseFormPage.vue"),
    props: true,
    meta: {
      permission: "update-warehouse",
      permissionAll: ["read-branch"],
    },
  },
  {
    path: "stocks",
    name: "stocks.index",
    component: () => import("./pages/StocksIndexPage.vue"),
    meta: { permission: ["read-stock", "create-stock", "update-stock"] },
  },
  {
    path: "stocks/create",
    name: "stocks.create",
    component: () => import("./pages/StockFormPage.vue"),
    meta: { permission: ["read-stock", "create-stock"] },
  },
  {
    path: "stocks/transfer",
    name: "stocks.transfer",
    component: () => import("./pages/StockTransferPage.vue"),
    meta: { permission: "transfer-stock" },
  },
  {
    path: "stock-transfer-logs",
    name: "stock-transfer-logs.index",
    component: () => import("./pages/StockTransferLogsIndexPage.vue"),
    meta: {
      permission: "read-stock-transfer",
      titleKey: "stockTransferLogs.title",
      breadcrumbKey: "stockTransferLogs.title",
      sidebarRoute: "stock-transfer-logs.index",
    },
  },
  {
    path: "stock-transfer-logs/:id",
    name: "stock-transfer-logs.show",
    component: () => import("./pages/StockTransferLogDetailsPage.vue"),
    props: true,
    meta: {
      permission: "read-stock-transfer",
      titleKey: "stockTransferLogs.detailsTitle",
      breadcrumbKey: "stockTransferLogs.detailsTitle",
      sidebarRoute: "stock-transfer-logs.index",
    },
  },
  {
    path: "stocks/:id/edit",
    name: "stocks.edit",
    component: () => import("./pages/StockFormPage.vue"),
    props: true,
    meta: { permission: ["read-stock", "update-stock"] },
  },
];
